### PR TITLE
moved swagger-ui to META-INF/static-content

### PR DESCRIPTION
**Pull request by dartartem**

### CODE REVIEW

**Comment by cer** [comment]
Please write tests for this specific issue and the issue fixed by previous PR

**Comment by dartartem** [comment]
Chris,

for this PR: https://github.com/eventuate-clients/eventuate-util/pull/10/files

we have tests in example applications that swagger-ut is available.
To test in here, I need to create some spring boot application with rest controller and write the same tests that it is available.
And I think test will have more code than solution itself. Please confirm that I should do it, or maybe you see more optimal way to test it.

Could you please also clarify what to test here: https://github.com/eventuate-clients/eventuate-util/pull/11/files

I just placed swagger-ui in subfolder of META-INF.

Should I check that jar-file contains swagger-ui files in META-INF/static-content?

**Comment by cer** [comment]
Code in other projects does not test this project.

This code is simple yet this is the second bug.

Please write some tests that use @springboottest random port and verify that the swagger UI works.

**Comment by dartartem** [comment]
Ok, I will write a spring test that checks swagger-ui. Thank you for clarification.

**Pull request merged**
